name: Publish on NuGet
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - run: dotnet tool restore
      - run: dotnet restore
      - run: dotnet paket restore
      - name: Build the package
        run: dotnet build --no-restore src/Feliz.ReactNative.fsproj
      - name: Publish the package
        run: dotnet nuget push src/bin/Release/*.nupkg --api-key ${{secrets.NUGET_AUTH_TOKEN}}